version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@octokit/types"
    versions:
    - 6.13.0
    - 6.13.1
    - 6.13.2
    - 6.14.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.36
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: "@vercel/ncc"
    versions:
    - 0.28.0
    - 0.28.1
    - 0.28.2
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.21.0
